import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { useRouter } from "next/router";
import * as Type from "../redux/auth/type";
import { FiSearch } from "react-icons/fi";
import Slider from "react-slick";

// custom components
import ChattingLayout from "../layouts/ChattingLayout";
import style from "../styles/pages/Home.module.css";
import Link from "next/link";

import { database, userId as FirebaseUserId } from "../firebase";
import { ref, onValue, set } from "firebase/database";
import moment from "moment";

const userId = 1;

function Chatting() {
  const messagesEndRef = React.useRef(null);
  const [messages, setMessages] = React.useState([]);
  const [keys, setKeys] = React.useState([]);

  React.useEffect(() => {
    const starCountRef = ref(database, `messages/${userId}`);

    scrollToBottom();

    onValue(starCountRef, (snapshot) => {
      const data = snapshot.val();

      if (data && typeof data === "object") {
        setMessages(data);
        setKeys(Object.keys(data));

        scrollToBottom();
      }
    });
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <div id="home" className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <ChattingLayout>
            <div
              style={{
                display: "block",
                width: "90%",
              }}
            >
              {keys?.map((item) => {
                let current = messages[item];

                if (current.user_id === FirebaseUserId)
                  return <SenderBox {...current} />;
                if (current.user_id !== FirebaseUserId)
                  return <ReceiverBox {...current} />;
              })}

              <div ref={messagesEndRef} />
            </div>
          </ChattingLayout>
        </main>
      </div>
    </>
  );
}

const SenderBox = (props) => (
  <div
    style={{
      width: "100%",
      display: "flex",
      justifyContent: "flex-end",
      margin: "10px",
    }}
  >
    <div>
      <div
        style={{
          marginTop: "20px",
          display: "inline-block",
          background: "#EEC302",
          borderRadius: "15px",
          padding: "15px",
          color: "#fff",
          boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.1)",
        }}
      >
        <span>{props.message}</span>
        <div style={{ display: "flex", gap: "5px" }}>
          <small style={{ color: "#fff", fontSize: "11px" }}>
            {moment(props.message_time).format("HH:mm")}
          </small>
          {props?.message_status === "sended" ? (
            <small style={{ color: "#fff", fontSize: "11px" }}>&#10003;</small>
          ) : (
            <small style={{ color: "#fff", fontSize: "11px" }}>x</small>
          )}
        </div>
      </div>
    </div>
  </div>
);

const ReceiverBox = (props) => (
  <div
    style={{
      width: "100%",
      display: "block",
    }}
  >
    <div>
      <div
        style={{
          marginTop: "20px",
          display: "inline-block",
          background: "#FFFFFF",
          borderRadius: "15px",
          padding: "15px",
          color: "#3E2B31",
          boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.1)",
        }}
      >
        <span>{props.message}</span>
        <div
          style={{
            display: "flex",
            gap: "5px",
            justifyContent: "flex-end",
          }}
        >
          <small style={{ color: "#3E2B31", fontSize: "11px" }}>
            {moment(props.message_time).format("HH:mm")}
          </small>
          {props?.message_status === "sended" ? (
            <small style={{ color: "#3E2B31", fontSize: "11px" }}>
              &#10003;
            </small>
          ) : (
            <small style={{ color: "#3E2B31", fontSize: "11px" }}>x</small>
          )}
        </div>
      </div>
    </div>
  </div>
);

export default Chatting;
